// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZm3ipJFIMwWdDpaD0c_ZuszJP8rH9pAg',
    appId: '1:888958928898:web:f61b0ed05aa9ab0d05bf1b',
    messagingSenderId: '888958928898',
    projectId: 'db2b-ea049',
    authDomain: 'db2b-ea049.firebaseapp.com',
    storageBucket: 'db2b-ea049.firebasestorage.app',
    measurementId: 'G-MW72N5W3QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnS-u2kMr5Zb-4QLt3BCZXTBGPJtQBSX8',
    appId: '1:888958928898:android:85515664ca9d435805bf1b',
    messagingSenderId: '888958928898',
    projectId: 'db2b-ea049',
    storageBucket: 'db2b-ea049.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO7GVZrD2fG9TVBieGP73aA09likiUhMA',
    appId: '1:888958928898:ios:8af1376db1ac1a1c05bf1b',
    messagingSenderId: '888958928898',
    projectId: 'db2b-ea049',
    storageBucket: 'db2b-ea049.firebasestorage.app',
    iosBundleId: 'com.example.db2b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO7GVZrD2fG9TVBieGP73aA09likiUhMA',
    appId: '1:888958928898:ios:8af1376db1ac1a1c05bf1b',
    messagingSenderId: '888958928898',
    projectId: 'db2b-ea049',
    storageBucket: 'db2b-ea049.firebasestorage.app',
    iosBundleId: 'com.example.db2b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZm3ipJFIMwWdDpaD0c_ZuszJP8rH9pAg',
    appId: '1:888958928898:web:a0efe614fc6f1d0a05bf1b',
    messagingSenderId: '888958928898',
    projectId: 'db2b-ea049',
    authDomain: 'db2b-ea049.firebaseapp.com',
    storageBucket: 'db2b-ea049.firebasestorage.app',
    measurementId: 'G-Q19EEVS901',
  );

}